# Generated by Django 4.0.3 on 2022-03-28 15:31

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import personal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrosel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem_name', models.CharField(max_length=32, verbose_name='Nome da Imagem')),
                ('imagem', models.ImageField(upload_to=personal.models.local_upload, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Imagem do Produto')),
            ],
            options={
                'verbose_name': 'Imagem',
                'verbose_name_plural': '(02) - Imagens',
            },
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_name', models.CharField(max_length=32, verbose_name='Nome do Produto')),
                ('descricao', ckeditor.fields.RichTextField(max_length=640)),
                ('status', models.BooleanField(default=True, verbose_name='Status do Produto')),
                ('data_insercao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Inserção')),
                ('imagem', models.ImageField(upload_to=personal.models.local_upload, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])], verbose_name='Imagem do Produto')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': '(01) - Produtos',
            },
        ),
    ]
